# The influxdbData and grafanaData instances mounting pysical directory in host OS. 
# The directories have to be created if does not exists. (With sudo)
#  mkdir -p /var/lib/docker/shared-volumes/grafana/logs
#  mkdir -p /var/lib/docker/shared-volumes/grafana/data
#  mkdir -p /var/lib/docker/shared-volumes/influxdb
#  chmod 1777 /var/lib/docker/shared-volumes -R

influxdbData:
  image: busybox
  volumes:
    - /var/lib/docker/shared-volumes/influxdb:/data

grafanaData:
  image: busybox
  volumes:
    - /var/lib/docker/shared-volumes/grafana/logs:/var/log/grafana
    - /var/lib/docker/shared-volumes/grafana/data:/var/lib/grafana

influxdb:
  image: blackbelt/influxdb:latest
  ports:
    - "20083:8083"
    - "20086:8086"
    - "20026:25826/udp"
    - "20003:2003"
  expose:
    - "8090"
    - "8099"
  volumes_from:
    - "influxdbData"

grafana:
  image: blackbelt/grafana:latest
  ports:
    - "20082:3000"
  volumes_from:
    - "grafanaData"
  links:
    - influxdb:influxsrv

init:
  build: monitoring-init
  links:
    - grafana:grafanasrv

